version: '3'

services:
  s3:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: "8P63VX5Qh8KWcnuVmDAjQ687LdV3n5"
      MINIO_SECRET_KEY: "Z4aPQZ3uxmVJkfhuR73GZzVLaymnAJGsAh9XYANyYYcjCcWFEFFACC3fPeYagUnmignFUCxQF46Qz9TG"
    volumes:
      - /srv/dev-disk-by-uuid-8b938487-3837-4817-b082-33293ab9b6c6/global-sync/Sync/Samba/ServerShare/s3/data:/data
      - /srv/dev-disk-by-uuid-8b938487-3837-4817-b082-33293ab9b6c6/global-sync/Sync/Samba/ServerShare/s3/config-kws:/root/.minio
    command: "minio server /data --address :9000 --console-address :9001"
